version: '3.8'

services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
  redis:
    extends:
      file: docker-compose.yml
      service: redis
  opensearch:
    image: opensearchproject/opensearch:latest
    ports:
      - "9400:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
  pgsync:
    extends:
      file: docker-compose.yml
      service: pgsync
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to OpenSearch sync"
      com.label-schema.service-type: "daemon"
    depends_on:
      - postgres
      - redis
      - opensearch
    environment:
      - ELASTICSEARCH=false
      - OPENSEARCH=true
